services:
  web:
    build:
      context: .
      dockerfile: dockerfile

    container_name: container
    image: image

    stdin_open: true
    tty: true
    restart: always

    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "1G"

    ports:
      - "3000:3000"
    network_mode: bridge
